plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

repositories {
    maven { url = "https://maven.shedaniel.me/" } // Cloth Config, REI
    maven { url = "https://dvs1.progwml6.com/files/maven/" } // JEI
    maven { url = "https://maven.parchmentmc.org" } // Parchment Mappings
    maven { url = "https://maven.quiltmc.org/repository/release" } // Quilt Mappings
    maven { url = "https://api.modrinth.com/maven" } // LazyDFU
    maven { url = "https://maven.terraformersmc.com/releases/" } // Mod Menu, Trinkets
    maven { url = "https://mvn.devos.one/snapshots/" } // Create, Porting Lib, Forge Tags, Milk Lib, Registrate
    maven { url = "https://cursemaven.com" } // Forge Config API Port
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
    maven { url = "https://jitpack.io/" } // Mixin Extras, Fabric ASM
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // Forge Config API Port
    maven { url = "https://modmaven.dev" } // Flywheel
    maven { url = "https://maven.ladysnake.org/releases" } // Trinkets
    maven { url = "https://api.modrinth.com/maven" } // Ad Astra
    maven { url = "https://maven.wispforest.io/releases/" } // Star Fluid
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings(loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    })
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    // Create - dependencies are added transitively
    modImplementation("com.simibubi.create:create-fabric-${minecraft_version}:${create_version}")

    // Development QOL
    modLocalRuntime("maven.modrinth:lazydfu:${lazydfu_version}")
    modLocalRuntime("com.terraformersmc:modmenu:${modmenu_version}")

    // Trinkets
    modImplementation("dev.emi:trinkets:${project.trinkets_version}")

    // Another Furniture
    modImplementation("maven.modrinth:another-furniture:${another_furniture_version}")

    // Hephaestus
	modImplementation("slimeknights.tconstruct:Hephaestus:${minecraft_version}-${hephaestus_version}") {
		// Nope get out
		exclude(group: "mcjty.theoneprobe")
		exclude(group: "me.alphamode")
	}
	modImplementation("slimeknights.mantle:Mantle:${minecraft_version}-${mantle_version}") {
		exclude(group: "me.alphamode")
	}
    modLocalRuntime("me.alphamode:Star:${star_version}+${minecraft_version}")

    // Ad Astra
    modImplementation("maven.modrinth:ad-astra:${ad_astra_version}")
    modLocalRuntime("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    modLocalRuntime("teamreborn:energy:${teamreborn_energy_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
}

configurations.all {
    resolutionStrategy {
        force("net.fabricmc:fabric-loader:${fabric_loader_version}")
        force("io.github.fabricators_of_create:porting_lib:${porting_lib_version}")
    }
}

processResources {
    // Require dependencies to be the version compiled against or newer
    Map<String, String> properties = new HashMap<>()
    properties.put("version", version)
    properties.put("fabric_loader_version", fabric_loader_version)
    properties.put("fabric_api_version", fabric_api_version)
    properties.put("create_version", create_version)
    properties.put("minecraft_version", minecraft_version)

    properties.forEach((k, v) -> inputs.property(k, v))

    filesMatching("fabric.mod.json") {
        expand properties
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// Configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
